pipeline {
  agent any
  parameters {
    booleanParam(defaultValue: false, description: "Enable service?", name: "myBoolean")
  }
  stages {
    stage("Demo") {
      steps {
        myFunc("Hello from the demo stage!")
      }
    }
  }
}

def myFunc(String myText) {
  echo "myText is set to: ${myText}"
}
