pipeline {
  agent any
  parameter {
    booleanParam(defaultValue: false, description: "Enable service?", name: "myBoolean")
  }
  stages {
    stage("Demo") {
      steps {
        echo "booleanParam is set to: ${params.myBoolean}"
      }
    }
  }
}
