pipeline {
  agent any
  parameters {
    choice(choices: ["TEST", "DEV", "QA", "PRE-PROD", "PROD"], description: "Which env to deploy in?", name: "deployEnv")
  }
  stages {
    stage("Demo") {
      steps {
        echo "choice is set to: ${params.deployEnv}"
      }
    }
  }
}
